-- FitRight: workout_summaries base schema (idempotent) + the columns the
-- AI post-workout report needs + a workout_reports cache table.
--
-- Every new column here holds already-aggregated, already-derived numbers
-- or counts — never raw pose/landmark/video data. See
-- src/lib/supabase.ts (toSummaryRow, aggregateFormFlags) for the client
-- side of this contract, and
-- supabase/functions/generate-workout-report/privacyGuard.ts for the
-- server side.

create table if not exists workout_summaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users not null,
  exercise_id text not null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  duration_sec int not null,
  reps int not null,
  form_score int not null,
  flag_count int not null,
  created_at timestamptz default now()
);

alter table workout_summaries
  add column if not exists sets_completed int not null default 0,
  add column if not exists target_reps int not null default 0,
  add column if not exists target_sets int not null default 0,
  add column if not exists form_flag_breakdown jsonb not null default '[]'::jsonb;

comment on column workout_summaries.form_flag_breakdown is
  'Aggregated per-rule-code counts for this session, e.g. '
  '[{"code":"back-lean","label":"Keep your chest up...","severity":"warning","count":6}]. '
  'Never raw per-frame, per-timestamp, or positional pose data.';

alter table workout_summaries enable row level security;

drop policy if exists "Users manage their own summaries" on workout_summaries;
create policy "Users manage their own summaries"
  on workout_summaries for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists workout_summaries_user_started_idx
  on workout_summaries (user_id, started_at desc);

-- Cache table for generated reports — one row per session. The
-- generate-workout-report edge function checks this first so a session's
-- report is generated by Gemini at most once (see its rate-limit note).
create table if not exists workout_reports (
  session_id uuid primary key references workout_summaries(id) on delete cascade,
  user_id uuid references auth.users not null,
  report jsonb not null,
  source text not null check (source in ('ai', 'fallback')),
  created_at timestamptz not null default now()
);

alter table workout_reports enable row level security;

-- Users may read their own cached reports directly (defense in depth /
-- future flexibility). There is deliberately no insert/update/delete
-- policy for the `authenticated` role — only the edge function, using the
-- service_role key (which bypasses RLS), is allowed to write a report.
drop policy if exists "Users read their own workout reports" on workout_reports;
create policy "Users read their own workout reports"
  on workout_reports for select
  using (auth.uid() = user_id);

create index if not exists workout_reports_user_created_idx
  on workout_reports (user_id, created_at desc);
